### ISSUE TITLE
support /dev/tty

### ISSUE THREAD

**Issue by quininer** [murarth/mortal#3]
Sometimes we don't want to write output to stdout.

I'm not sure what to do with Windows, but at least we can have a `TerminalExt`.

**Comment by murarth** [comment]
I've added a commit implementing this functionality under a new Unix-only extension trait. The method couldn't be added to the existing trait because that trait is also implemented for lock guard types, which cannot be created this way.

Let me know if this fits your use case and if there are any issues with the implementation.

**Comment by quininer** [comment]
Thanks you.

I still want Windows support, but I'm satisfied with it at the moment.
